### PR TITLE
Add SlaManagementUI to docker compose

### PR DESCRIPTION
**Pull request by rosogon**
SlaManagement UI is running on port 8000 inside slalite-ui component. Exposed to the outside as :48000.

@cjdcordeiro : please, confirm you agree accessing it through 48000 or suggest other port.

Thanks

### CODE REVIEW

**Comment by rosogon** [comment]
I guess yes. Do you mean redirecting f.e. sla-ui on :80, :443 to http://slalite-ui:8000?

**Comment by cjdcordeiro** [comment]
yes, under the prefix /sla/ for example

**Comment by rosogon** [comment]
Thanks, @cjdcordeiro.

> it doesn't seem to work cause it is redirect traffic to port 8000

If you talk about the error in the health script, it is now fixed (it now checks /sla).

Anyway, I pushed a new image (0.1.2) that simplifies the connection to CIMI. 

Docs also added.

**Comment by cjdcordeiro** [comment]
it still has the same issue. If I type `localhost/sla` I'm redirected to `localhost:8000/sla` which doesn't exist

**Comment by rosogon** [comment]
¿Are you connecting to https?

**Comment by rosogon** [comment]
@cjdcordeiro. Issue was nginx serving UI was accepting `localhost/sla/`, but not `localhost/sla`. Now fixed.

**Pull request merged**
