### PR TITLE
Added cau-client and aclib integration tests

### PR DESCRIPTION
**Pull request by syc17**
Hi could you approve this PR, ta.

### CODE REVIEW

**Comment by cjdcordeiro** [comment]
can you paste the output of the `hello-world.sh --include-tests`?

**Comment by syc17** [comment]
[root@stfc-tests docker-compose]# docker system prune
WARNING! This will remove:
        - all stopped containers
        - all networks not used by at least one container
        - all dangling images
        - all dangling build cache
Are you sure you want to continue? [y/N] 7
[root@stfc-tests docker-compose]# docker system prune
WARNING! This will remove:
        - all stopped containers
        - all networks not used by at least one container
        - all dangling images
        - all dangling build cache
Are you sure you want to continue? [y/N] y
Total reclaimed space: 0B
[root@stfc-tests docker-compose]# ls ./tests/
aclib.sh  cau-client.sh  cimi.sh  service-manager.sh  vpnclient.sh
[root@stfc-tests docker-compose]# ls -l ./tests/
total 32
-rwxr-xr-x. 1 root  root  5076 Aug 14 13:44 aclib.sh
-rwxr-xr-x. 1 root  root  2129 Aug 14 13:44 cau-client.sh
-rwxr-xr-x. 1 root  root  4385 Aug  7 13:51 cimi.sh
-rwxrwxr-x. 1 syc17 syc17 2888 May 31 15:28 service-manager.sh
-rwxr-xr-x. 1 root  root  6194 Aug 12 19:45 vpnclient.sh
[root@stfc-tests docker-compose]#  docker-compose -p mf2c up -d
WARNING: The Docker Engine you're using is running in swarm mode.

Compose does not use swarm mode to deploy services to multiple nodes in a swarm. All containers will be scheduled on the current node.

To deploy your application across the swarm, use `docker stack deploy`.

Creating network "mf2c_default" with the default driver
Creating volume "mf2c_mydata" with default driver
Creating volume "mf2c_influx" with default driver
Creating volume "mf2c_influx-analytics" with default driver
Creating volume "mf2c_neo4j" with default driver
Creating volume "mf2c_landscaper" with default driver
Creating volume "mf2c_ringcontainer" with default driver
Creating volume "mf2c_ringcontainerexample" with default driver
Creating volume "mf2c_pkidata" with default driver
Creating mf2c_slalite_1          ... done
Creating mf2c_identification_1   ... done
Creating mf2c_logicmodule1_1   ... done
Creating mf2c_proxy_1          ... done
Creating mf2c_influxdb_1       ... done
Creating mf2c_rc_1               ... done
Creating mf2c_neo4j_1          ... done
Creating mf2c_snap_1             ... done
Creating mf2c_analytics-engine_1 ... done
Creating mf2c_ds1java1_1         ... done
Creating mf2c_dcproxy_1          ... done
Creating mf2c_telem_start_1      ... done
Creating mf2c_cimi_1             ... done
Creating mf2c_event-manager_1      ... done
Creating mf2c_policies_1           ... done
Creating mf2c_service-manager_1    ... done
Creating mf2c_discovery_1          ... done
Creating mf2c_landscaper_1              ... done
Creating mf2c_resource-bootstrap_1 ... done
Creating mf2c_cau-client_1              ... done
Creating mf2c_resource-categorization_1 ... done
Creating mf2c_web_1                     ... done
Creating mf2c_lm-um_1                   ... done
Creating mf2c_aclib_1                   ... done
Creating mf2c_vpnclient_1               ... done
[root@stfc-tests docker-compose]# docker cp /home/centos/server.key mf2c_aclib_1:/pkidata/server.cert
[root@stfc-tests docker-compose]# docker cp /home/centos/server.key mf2c_aclib_1:/pkidata/server.key
[root@stfc-tests docker-compose]# docker cp /home/centos/server.crt  mf2c_aclib_1:/pkidata/server.crt
[root@stfc-tests docker-compose]# docker cp /home/centos/deviceid.txt  mf2c_aclib_1:/pkidata/deviceid.txt
[root@stfc-tests docker-compose]# docker exec -it mf2c_aclib_1 -sh -c "ls -l /pkidata/"
OCI runtime exec failed: exec failed: container_linux.go:345: starting container process caused "exec: \"-sh\": executable file not found in $PATH": unknown
[root@stfc-tests docker-compose]# docker exec -it mf2c_aclib_1 sh -c "ls -l /pkidata/"
total 24
-rw-------    1 root     root          1625 Aug 14 11:59 client.ovpn
-rw-rw-r--    1 1001     1001           128 Aug  9 15:05 deviceid.txt
-rw-r--r--    1 root     root          1460 Aug 14 11:57 fogca.pem
-rw-rw-r--    1 1001     1001          1744 Aug  9 15:05 server.cert
-rw-rw-r--    1 1001     1001          1744 Aug  9 15:05 server.crt
-rw-rw-r--    1 1001     1001          1744 Aug  9 15:05 server.key
[root@stfc-tests docker-compose]# ./hello-world.sh --include-tests
 Tester needs privilege to run Docker commands...
 Tests will be aborted if Agent does not have the necessary mF2C cedentials...
 [ACLibTests]     Starting...
Extracting container id ....
Checking if agent credentials exist....
Setting ACLib IP...
network id: mf2c_default
ALib host ip set to 172.27.0.24
 [ACLibTests]     SUCCESS: Got JWT from ACLib
 [ACLibTests]     SUCCESS: JWT verified by ACLib
The payload: a top secret message!
 [ACLibTests]     SUCCESS: JWS created by ACLib
verified JWS payload: a top secret message!
 [ACLibTests]     SUCCESS: JWS verfied by ACLib
 [ACLibTests]     SUCCESS: JWE with payload compression created by ACLib
verified JWE payload: a top secret message!
 [ACLibTests]     SUCCESS: JWE with payload compression verfied by ACLib
End of ACLib Tests.....
 Tester needs privilege to run Docker commands...
 Tests will be aborted if Agent does not have the necessary mF2C cedentials...
 [ACLibTests]     Starting...
Extracting container id ....
Checking if agent credentials exist....
Setting ACLib IP...
network id: mf2c_default
ALib host ip set to 172.27.0.24
 [ACLibTests]     SUCCESS: Got JWT from ACLib
 [ACLibTests]     SUCCESS: JWT verified by ACLib
The payload: a top secret message!
 [ACLibTests]     SUCCESS: JWS created by ACLib
verified JWS payload: a top secret message!
 [ACLibTests]     SUCCESS: JWS verfied by ACLib
 [ACLibTests]     SUCCESS: JWE with payload compression created by ACLib
verified JWE payload: a top secret message!
 [ACLibTests]     SUCCESS: JWE with payload compression verfied by ACLib
End of ACLib Tests.....
 Tester needs privilege to run Docker commands...
 Tests will be aborted if Agent does not have the necessary mF2C cedentials...
 [ACLibTests]     Starting...
Extracting container id ....
Checking if agent credentials exist....
Setting ACLib IP...
network id: mf2c_default
ALib host ip set to 172.27.0.24
 [ACLibTests]     SUCCESS: Got JWT from ACLib
 [ACLibTests]     SUCCESS: JWT verified by ACLib
The payload: a top secret message!
 [ACLibTests]     SUCCESS: JWS created by ACLib
verified JWS payload: a top secret message!
 [ACLibTests]     SUCCESS: JWS verfied by ACLib
 [ACLibTests]     SUCCESS: JWE with payload compression created by ACLib
verified JWE payload: a top secret message!
 [ACLibTests]     SUCCESS: JWE with payload compression verfied by ACLib
End of ACLib Tests.....
 Tester needs privilege to run Docker commands...
 Tests will be aborted if Agent does not have the necessary mF2C cedentials...
 [ACLibTests]     Starting...
Extracting container id ....
Checking if agent credentials exist....
Setting ACLib IP...
network id: mf2c_default
ALib host ip set to 172.27.0.24
 [ACLibTests]     SUCCESS: Got JWT from ACLib
 [ACLibTests]     SUCCESS: JWT verified by ACLib
The payload: a top secret message!
 [ACLibTests]     SUCCESS: JWS created by ACLib
verified JWS payload: a top secret message!
 [ACLibTests]     SUCCESS: JWS verfied by ACLib
 [ACLibTests]     SUCCESS: JWE with payload compression created by ACLib
verified JWE payload: a top secret message!
 [ACLibTests]     SUCCESS: JWE with payload compression verfied by ACLib
End of ACLib Tests.....
 Tester needs privilege to run Docker commands...
 Tests will be aborted if Agent does not have the necessary mF2C cedentials...
 [ACLibTests]     Starting...
Extracting container id ....
Checking if agent credentials exist....
Setting ACLib IP...
network id: mf2c_default
ALib host ip set to 172.27.0.24
 [ACLibTests]     SUCCESS: Got JWT from ACLib
 [ACLibTests]     SUCCESS: JWT verified by ACLib
The payload: a top secret message!
 [ACLibTests]     SUCCESS: JWS created by ACLib
verified JWS payload: a top secret message!
 [ACLibTests]     SUCCESS: JWS verfied by ACLib
 [ACLibTests]     SUCCESS: JWE with payload compression created by ACLib
verified JWE payload: a top secret message!
 [ACLibTests]     SUCCESS: JWE with payload compression verfied by ACLib
End of ACLib Tests.....
 [HelloWorldTest]  Starting...
 [ResourceCategorization]  FAILED:  no device dynamic was added
 [SLAManager]             SUCCESS: service sla-template/143774b4-f3e1-4b14-922a-ecbb05b34716 created successfully
 [ServiceManager]         SUCCESS: service "service/e8c7c231-9777-479d-a807-c1d10c220067" created successfully
parse error: Invalid numeric literal at line 1, column 8
 [Analytics]              FAILED:  failed to return list of ip addresses
jq: error (at <stdin>:1): Cannot iterate over null (null)
 [LifecycleManager]       FAILED:  failed to launch service instance
 [HelloWorldTest]         FAILED:  ip address from service instance [] does not match with ip from analytics []
 [LifecycleManager]       INFO:    Service instance status = 405...
 [SlaManagement]          FAILED:  Failed to create agreement
[root@stfc-tests docker-compose]#

**Comment by syc17** [comment]
I ran the hello-world tests,  and I notice a few things:
1) not all the tests were run, not sure why.  E.g. no CIMI, no cau-client, no vpn client tests
2) aclib tests: you told me to fail the tests if the preconditions are not met.  So I had to copy the credentials files to the container to make sure the tests ran.  I don't think you do any discovery with the hello-world, so there wouldn't be any credentials created w/o the discovery, reg and authen processes.

**Comment by cjdcordeiro** [comment]
you've copied the credentials files from where?

**Comment by syc17** [comment]
I got those from my own unit testing.  The key is generated by the CAU-Client, the cert got via the CAU from the cloud CA, I made up my own deviceid according to the agreed convention with UPC

**Comment by cjdcordeiro** [comment]
ok but please run the tests without any magic. So remove these lines
```
[root@stfc-tests docker-compose]# docker cp /home/centos/server.key mf2c_aclib_1:/pkidata/server.key
[root@stfc-tests docker-compose]# docker cp /home/centos/server.crt mf2c_aclib_1:/pkidata/server.crt
[root@stfc-tests docker-compose]# docker cp /home/centos/deviceid.txt mf2c_aclib_1:/pkidata/deviceid.txt
[root@stfc-tests docker-compose]# docker exec -it mf2c_aclib_1 sh -c "ls -l /pkidata/"```

even if it fails...

**Comment by syc17** [comment]
[root@stfc-tests docker-compose]# docker system prune
WARNING! This will remove:
        - all stopped containers
        - all networks not used by at least one container
        - all dangling images
        - all dangling build cache
Are you sure you want to continue? [y/N] y
Total reclaimed space: 0B
[root@stfc-tests docker-compose]# docker-compose -p mf2c up -d
WARNING: The Docker Engine you're using is running in swarm mode.

Compose does not use swarm mode to deploy services to multiple nodes in a swarm. All containers will be scheduled on the current node.

To deploy your application across the swarm, use `docker stack deploy`.

Creating network "mf2c_default" with the default driver
Creating volume "mf2c_mydata" with default driver
Creating volume "mf2c_influx" with default driver
Creating volume "mf2c_influx-analytics" with default driver
Creating volume "mf2c_neo4j" with default driver
Creating volume "mf2c_landscaper" with default driver
Creating volume "mf2c_ringcontainer" with default driver
Creating volume "mf2c_ringcontainerexample" with default driver
Creating volume "mf2c_pkidata" with default driver
Creating mf2c_neo4j_1          ... done
Creating mf2c_proxy_1          ... done
Creating mf2c_influxdb_1       ... done
Creating mf2c_identification_1 ... done
Creating mf2c_slalite_1        ... done
Creating mf2c_logicmodule1_1   ... done
Creating mf2c_rc_1             ... done
Creating mf2c_ds1java1_1         ... done
Creating mf2c_analytics-engine_1 ... done
Creating mf2c_snap_1             ... done
Creating mf2c_dcproxy_1          ... done
Creating mf2c_telem_start_1      ... done
Creating mf2c_cimi_1             ... done
Creating mf2c_service-manager_1         ... done
Creating mf2c_event-manager_1           ... done
Creating mf2c_discovery_1               ... done
Creating mf2c_landscaper_1              ... done
Creating mf2c_resource-bootstrap_1      ... done
Creating mf2c_policies_1           ... done
Creating mf2c_cau-client_1              ... done
Creating mf2c_resource-categorization_1 ... done
Creating mf2c_web_1                     ... done
Creating mf2c_aclib_1                   ... done
Creating mf2c_vpnclient_1               ... done
Creating mf2c_lm-um_1                   ... done
[root@stfc-tests docker-compose]# ls -l ./tests/
total 32
-rwxr-xr-x. 1 root  root  5076 Aug 14 13:44 aclib.sh
-rwxr-xr-x. 1 root  root  2129 Aug 14 13:44 cau-client.sh
-rwxr-xr-x. 1 root  root  4385 Aug  7 13:51 cimi.sh
-rwxrwxr-x. 1 syc17 syc17 2888 May 31 15:28 service-manager.sh
-rwxr-xr-x. 1 root  root  6194 Aug 12 19:45 vpnclient.sh
[root@stfc-tests docker-compose]# ./hello-world.sh --include-tests
 Tester needs privilege to run Docker commands...
 Tests will be aborted if Agent does not have the necessary mF2C cedentials...
 [ACLibTests]     Starting...
Extracting container id ....
Checking if agent credentials exist....
 [ACLibTests]     FAILED: No /pkidata/deviceid.txt file, cannot proceed!
 Tester needs privilege to run Docker commands...
 Tests will be aborted if Agent does not have the necessary mF2C cedentials...
 [ACLibTests]     Starting...
Extracting container id ....
Checking if agent credentials exist....
 [ACLibTests]     FAILED: No /pkidata/deviceid.txt file, cannot proceed!
 Tester needs privilege to run Docker commands...
 Tests will be aborted if Agent does not have the necessary mF2C cedentials...
 [ACLibTests]     Starting...
Extracting container id ....
Checking if agent credentials exist....
 [ACLibTests]     FAILED: No /pkidata/deviceid.txt file, cannot proceed!
 Tester needs privilege to run Docker commands...
 Tests will be aborted if Agent does not have the necessary mF2C cedentials...
 [ACLibTests]     Starting...
Extracting container id ....
Checking if agent credentials exist....
 [ACLibTests]     FAILED: No /pkidata/deviceid.txt file, cannot proceed!
 Tester needs privilege to run Docker commands...
 Tests will be aborted if Agent does not have the necessary mF2C cedentials...
 [ACLibTests]     Starting...
Extracting container id ....
Checking if agent credentials exist....
 [ACLibTests]     FAILED: No /pkidata/deviceid.txt file, cannot proceed!
 [HelloWorldTest]  Starting...
parse error: Invalid numeric literal at line 1, column 4
 [ResourceCategorization]  FAILED:  no device dynamic was added
parse error: Invalid numeric literal at line 1, column 4
 [SLAManager]             FAILED:  failed to create new service
parse error: Invalid numeric literal at line 1, column 4
 [ServiceManager]         FAILED:  failed to create new service
parse error: Invalid numeric literal at line 1, column 8
 [Analytics]              FAILED:  failed to return list of ip addresses
jq: error (at <stdin>:1): Cannot iterate over null (null)
 [LifecycleManager]       FAILED:  failed to launch service instance
 [HelloWorldTest]         FAILED:  ip address from service instance [] does not match with ip from analytics []
parse error: Invalid numeric literal at line 1, column 4
 [LifecycleManager]       INFO:    Service instance status = ...
parse error: Invalid numeric literal at line 1, column 4
 [SlaManagement]          FAILED:  Failed to create agreement
[root@stfc-tests docker-compose]#

**Comment by syc17** [comment]
have updated hello-world.sh and here is the output:
[root@stfc-tests docker-compose]# docker exec -it mf2c_aclib_1 sh -c "ls -l /pkidata/"
total 8
-rw-r--r--    1 root     root          1460 Aug 14 13:55 fogca.pem
-rw-r--r--    1 root     root          1712 Aug 14 13:55 server.key
[root@stfc-tests docker-compose]# clear
[root@stfc-tests docker-compose]# ./hello-world.sh --include-tests
current test : aclib.sh...
 Tester needs privilege to run Docker commands...
 Tests will be aborted if Agent does not have the necessary mF2C cedentials...
 [ACLibTests]     Starting...
Extracting container id ....
Checking if agent credentials exist....
 [ACLibTests]     FAILED: No /pkidata/deviceid.txt file, cannot proceed!
current test : cau-client.sh...
 Tester needs privilege to run Docker commands...
 [CAU-ClientTests]
 Starting...
Extracting container id ....
cau-client container id : aa5ac70f3c2c
get cert returned : OK
 [CAU-ClientTests]  SUCCESS: Got cert from cau-client
the retrieved pubkey: -----BEGIN RSA PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsJ6bKSfD7av+lM7Kdm8UKlKcq1kzNVVJmVTYgmAaXCgBHGhttj3ndiVfHbwyIuEKI1qW7aMN1U4xBFack9NqfXJ6qHH9Fuv72PyUnZG5bnxys0I8CuJtyYgDu2ZdeNJV+9M6+k3MsXeHALUxB+As7ZG5e/L0L5ktgbiSlxYFoyTyDCyTTejBJscKZ+mKrCJ2iXG4bNBFAPiJ85sNyHNYVd9/M00gfzc4a9oDBDKGGDQQSE8RNreK8q77llXJSPQnmB80FKRSG1T/kTeFxgfrLzKocLBT6Ws8V3+xnFDCTtZ39vv2qERM87iRzQm6REVDVEnA073LBZu12Rlwp2J2/wIDAQAB-----END RSA PUBLIC KEY-----
 [CAU-ClientTests]  SUCCESS: Got public key from cau-client
 [CAU-ClientTests]  SUCCESS: COMPLETED CAU-CLIENT tests!
current test : cimi.sh...
 [CIMITests]      Starting...
 [CIMITests]      FAILED: unable to get cloud-entry-point
 [CIMITests]      FAILED: user authorization not working: public access to restricted resource
 [CIMITests]      FAILED: incorrect response: did not receive 405 for invalid resource collection
 [CIMITests]      FAILED: incorrect response: did not receive 404 for non-existent user
 [CIMITests]      FAILED: failed to create new user hvYrfMKt
 [CIMITests]      FAILED: no error or wrong error when trying to create hvYrfMKt a second time
parse error: Invalid numeric literal at line 1, column 4
 [CIMITests]      FAILED: failed to create new resource
 [CIMITests]      FAILED: failed to get resource by ID
 [CIMITests]      FAILED: failed perform a query with filters
 [CIMITests]      FAILED: failed to update resource
 [CIMITests]      FAILED: failed to delete user hvYrfMKt
current test : service-manager.sh...
 [SerivceManagerTests]  Starting...
parse error: Invalid numeric literal at line 1, column 4
 [SerivceManagerTests]  FAILED: failed to create new service
parse error: Invalid numeric literal at line 1, column 4
 [SerivceManagerTests]  FAILED: service  is not categorized
 [SerivceManagerTests]  FAILED: failed to launch service instance null
 [SerivceManagerTests]  FAILED: failed to check QoS for service instance null
parse error: Invalid numeric literal at line 1, column 4
 [SerivceManagerTests]  FAILED: QoS model for agreement null does not exist
current test : vpnclient.sh...
 [VPNclientTests]  Starting...
 [VPNclientTests]  SUCCESS: TUN device exists
 [VPNclientTests]  SUCCESS: TUN device is up
awk: cmd. line:30:     client=or(lshift(a[1],24), lshift(a[2],16), lshift(a[3],8), a[4])
awk: cmd. line:30:                                                                     ^ 4 is invalid as number of arguments for or
 [VPNclientTests]  FAILED: Failed to calculate server address
 [HelloWorldTest]  Starting...
parse error: Invalid numeric literal at line 1, column 4
 [ResourceCategorization]  FAILED:  no device dynamic was added
parse error: Invalid numeric literal at line 1, column 4
 [SLAManager]             FAILED:  failed to create new service
parse error: Invalid numeric literal at line 1, column 4
 [ServiceManager]         FAILED:  failed to create new service
parse error: Invalid numeric literal at line 1, column 8
 [Analytics]              FAILED:  failed to return list of ip addresses
jq: error (at <stdin>:1): Cannot iterate over null (null)
 [LifecycleManager]       FAILED:  failed to launch service instance
 [HelloWorldTest]         FAILED:  ip address from service instance [] does not match with ip from analytics []
parse error: Invalid numeric literal at line 1, column 4
 [LifecycleManager]       INFO:    Service instance status = ...
parse error: Invalid numeric literal at line 1, column 4
 [SlaManagement]          FAILED:  Failed to create agreement

**Comment by syc17** [comment]
After updating hello-world.sh:

[root@stfc-tests docker-compose]# ./hello-world.sh --include-tests
Current test: aclib.sh...
 Tester needs privilege to run Docker commands...
 Tests will be aborted if Agent does not have the necessary mF2C cedentials...
 [ACLibTests]     Starting...
Extracting container id ....
Checking if agent credentials exist....
 [ACLibTests]     FAILED: No /pkidata/deviceid.txt file, cannot proceed!
Current test: cau-client.sh...
 Tester needs privilege to run Docker commands...
 [CAU-ClientTests]
 Starting...
Extracting container id ....
cau-client container id : 3546402832f8
the retrieved pubkey: -----BEGIN RSA PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsJ6bKSfD7av+lM7Kdm8UKlKcq1kzNVVJmVTYgmAaXCgBHGhttj3ndiVfHbwyIuEKI1qW7aMN1U4xBFack9NqfXJ6qHH9Fuv72PyUnZG5bnxys0I8CuJtyYgDu2ZdeNJV+9M6+k3MsXeHALUxB+As7ZG5e/L0L5ktgbiSlxYFoyTyDCyTTejBJscKZ+mKrCJ2iXG4bNBFAPiJ85sNyHNYVd9/M00gfzc4a9oDBDKGGDQQSE8RNreK8q77llXJSPQnmB80FKRSG1T/kTeFxgfrLzKocLBT6Ws8V3+xnFDCTtZ39vv2qERM87iRzQm6REVDVEnA073LBZu12Rlwp2J2/wIDAQAB-----END RSA PUBLIC KEY-----
 [CAU-ClientTests]  SUCCESS: Got public key from cau-client
 [CAU-ClientTests]  SUCCESS: COMPLETED CAU-CLIENT tests!
Current test: cimi.sh...
 [CIMITests]      Starting...
 [CIMITests]      SUCCESS: cloud-entry-point exists
 [CIMITests]      SUCCESS: user authorization working properly
 [CIMITests]      SUCCESS: correct 405 on invalid resource collection
 [CIMITests]      SUCCESS: correct 404 for non-existent user
 [CIMITests]      SUCCESS: user VJJFpSQO created successfully
 [CIMITests]      FAILED: no error or wrong error when trying to create VJJFpSQO a second time
parse error: Invalid numeric literal at line 1, column 10
 [CIMITests]      FAILED: failed to create new resource
 [CIMITests]      SUCCESS: successfully retrieved resource by ID
 [CIMITests]      SUCCESS: resource filtering is working
 [CIMITests]      FAILED: failed to update resource
 [CIMITests]      SUCCESS: user VJJFpSQO deleted successfully
Current test: service-manager.sh...
 [SerivceManagerTests]  Starting...
 [SerivceManagerTests]  SUCCESS: service "service/32b24be6-54f1-49ac-b721-12d1cc21f715" created successfully
 [SerivceManagerTests]  SUCCESS: service service/32b24be6-54f1-49ac-b721-12d1cc21f715 has category 0
 [SerivceManagerTests]  FAILED: failed to launch service instance null
 [SerivceManagerTests]  FAILED: failed to check QoS for service instance null
 [SerivceManagerTests]  FAILED: QoS model for agreement null does not exist
Current test: vpnclient.sh...
 [VPNclientTests]  Starting...
 [VPNclientTests]  FAILED: Timeout waiting for TUN device to appear, no TUN device
 [HelloWorldTest]  Starting...
 [ResourceCategorization]  FAILED:  no device dynamic was added
 [SLAManager]             SUCCESS: service sla-template/ce4ea1cb-dfa9-445f-b5dc-40d370d81764 created successfully
 [ServiceManager]         SUCCESS: service "service/16c80b9b-ee29-4396-8bc1-175b41cd44ec" created successfully
parse error: Invalid numeric literal at line 1, column 8
 [Analytics]              FAILED:  failed to return list of ip addresses
jq: error (at <stdin>:1): Cannot iterate over null (null)
 [LifecycleManager]       FAILED:  failed to launch service instance
 [HelloWorldTest]         FAILED:  ip address from service instance [] does not match with ip from analytics []
 [LifecycleManager]       INFO:    Service instance status = 405...
 [SlaManagement]          FAILED:  Failed to create agreement
[root@stfc-tests docker-compose]#

**Comment by syc17** [comment]
have pushed change to hello-world to git

**Pull request merged**
