### PR TITLE
Update resource bootstrap to v1.4.1.

### PR DESCRIPTION
**Pull request by sstanovnik**
Includes initial user force-activation.

Relevant commit: mf2c/resource-bootstrap@ade4400fa5d0c3a2f4d266235b8503f31fcf3130

### CODE REVIEW

**Comment by cjdcordeiro** [comment]
@ALEJANDROJ19 this should validate the user during the bootstrap. So identification must work

**Comment by cjdcordeiro** [comment]
@sstanovnik can you also add the docs?

**Comment by ALEJANDROJ19** [comment]
thanks @sstanovnik  @cjdcordeiro ! I'm already changing and testing the registration trigger to retry until the user is registered (only in cloud).

**Comment by cjdcordeiro** [comment]
@ALEJANDROJ19 thanks for looking into it. Can you create a ticket for it? SO that at least we know this exists, it can we face it again in the future. For now let's just live with dashboard then

**Pull request merged**
