### PR TITLE
Healthcheck for vpnclient

### LINKED ISSUE #259: healthcheck for vpnclient
Version 1.1.2 of vpnclient will support running healthchecks

### PR DESCRIPTION
**Pull request by jjensenral**
closes #259

### CODE REVIEW

**Comment by jjensenral** [comment]
Sorry, Cris, which docs? I've updated the docs in the vpn repo.

**Comment by jjensenral** [comment]
I suddenly twigged you might mean the results of the integration tests.  When I ported the test to the VPN client I discovered a bug in the integration test which I need to fix.. Possibly something has changhed in Alpine's busybox that has made a part of the code fail because it used to work.

**Comment by cjdcordeiro** [comment]
sry I mean this: https://github.com/mF2C/mF2C/blob/master/docs/vpnclient.md

you've upgraded the Docker Image so you need a new entry in the changelog

**Comment by jjensenral** [comment]
Ah, of course. Done. Added extensive update.
Thanks

**Pull request merged**
