### PR TITLE
mf2c.sh 1.4

### PR DESCRIPTION
**Pull request by ALEJANDROJ19**
solves: #323 

+ agentType env variable added and populated

- [ ] @ssgUPC check if env is set and res-cat is setting correctly the string in device resource.

### CODE REVIEW

**Comment by ALEJANDROJ19** [comment]
> the res-cat is not picking up that env - not working

- [ ] @ssgUPC https://github.com/mF2C/ResourceManagement/issues/80

**Comment by ssgUPC** [comment]
@ALEJANDROJ19 does you changes in script file, reflects to the following lines (https://github.com/mF2C/mF2C/blob/79298361908a512af1d1c0f729416d63c25ce00b/agent/docker-compose.yml#L342) in d-c file and can I get the environment variables info (value) from their?

**Comment by cjdcordeiro** [comment]
this one can only be merged once the res-cat is fixed. waiting for PR

**Comment by cjdcordeiro** [comment]
@ALEJANDROJ19 @ssgUPC status?

**Comment by ALEJANDROJ19** [comment]
> @ALEJANDROJ19 @ssgUPC status?

Waiting for PR from @ssgUPC

**Pull request merged**
